ReporteCaja.AplicacionWeb/ReporteCaja.AplicacionWeb/Controllers/AccesoController.cs
using Microsoft.AspNetCore.Mvc;

using ReporteCaja.AplicacionWeb.Models.ViewModels;
using ReporteCaja.BLL.Interfaces;
using ReporteCaja.Entity;

using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;

namespace ReporteCaja.AplicacionWeb.Controllers
{
    public class AccesoController : Controller
    {
        private readonly ICajaUsuariosServices _cajaUsuarioServices;

        public AccesoController(ICajaUsuariosServices cajaUsuarioServices)
        {
            _cajaUsuarioServices = cajaUsuarioServices;
        }

        [HttpGet]
        public IActionResult Login()
        {
            ClaimsPrincipal claimUser = HttpContext.User;
            if (claimUser.Identity.IsAuthenticated) // BOTON DE MANTENER SESION ABIERTA
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(VMCajaUsuarioLogin modelo)
        {
            CajaUsuario usuarioEncontrado = await _cajaUsuarioServices.ObtenerCredenciales(modelo.Correo, modelo.Clave);
            if (usuarioEncontrado == null)
            {
                ViewData["Mensaje"] = "No existe este usuario";
                return View();
            }

            ViewData["Mensaje"] = null;

            int rol = 0;
            if (usuarioEncontrado.Rol == "user") rol = 1;

            List<Claim> claims = new List<Claim>()
            {
                new Claim(ClaimTypes.Name, usuarioEncontrado.Nombre),
                new Claim(ClaimTypes.NameIdentifier, usuarioEncontrado.Id.ToString()),
                new Claim(ClaimTypes.Role, rol.ToString()),
                new Claim(ClaimTypes.Surname, usuarioEncontrado.SucursalId.ToString())
            };
            ClaimsIdentity cIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            AuthenticationProperties properties = new AuthenticationProperties()
            {
                AllowRefresh = true,
                IsPersistent = (Boolean)modelo.MantenerSesion
            };

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(cIdentity),
                properties);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult RestablecerClave()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> RestablecerClave(VMCajaUsuarioLogin modelo)
        {
            try
            {
                string urlPlantillaCorreo = $"{this.Request.Scheme}://{this.Request.Host}/Plantilla/RestablecerClave?clave=[clave]";
                bool resultado = await _cajaUsuarioServices.RestablecerClave(modelo.Correo, urlPlantillaCorreo);

                if (resultado)
                {
                    ViewData["Mensaje"] = "Contraseña restablecida. Revise su correo";
                    ViewData["MensajeError"] = null;
                }
                else
                {
                    ViewData["Mensaje"] = null;
                    ViewData["MensajeError"] = "No se pudo restablecer la contraseña. Por favor intente de nuevo mas tarde.";
                }
            }
            catch (Exception ex)
            {
                ViewData["Mensaje"] = null;
                ViewData["MensajeError"] = ex.Message;
            }

            return View();
        }
    }
}

ReporteCaja.AplicacionWeb/ReporteCaja.AplicacionWeb/Views/Acceso/Login.cshtml
@model ReporteCaja.AplicacionWeb.Models.ViewModels.VMCajaUsuarioLogin;
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="ES">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>GeoPedidos - Login</title>

    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Karla:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.8.95/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

    <link rel="stylesheet" href="~/css/login/login.css">
</head>
<body>
    <main class="d-flex align-items-center min-vh-100 py-3 py-md-0">
        <div class="container">
            <div class="card login-card">
                <div class="row no-gutters">
                    <div class="col-md-5">
                        <img src="~/images/login.jpg" alt="login" class="login-card-img">
                    </div>
                    <div class="col-md-7">
                        <div class="card-body">
                            <p class="login-card-description">Iniciar Sesion</p>
                            <form asp-controller="Acceso" asp-action="Login" method="post">
                                <div class="form-group">
                                    <label for="email" class="sr-only">Email</label>
                                    <input type="email" asp-for="Correo" class="form-control" placeholder="Email">
                                </div>
                                <div class="form-group mb-4">
                                    <label for="password" class="sr-only">Password</label>
                                    <input type="password" asp-for="Clave" class="form-control" placeholder="***********">
                                </div>
                                <div class="form-group mb-3">
                                    <input type="checkbox" class="custom-control-input" id="chkMantenerSesion" asp-for="MantenerSesion">
                                    <label class="custom-control-label" for="chkMantenerSesion">Mantener Sesión</label>
                                </div>
                                <input name="login" id="login" class="btn btn-block login-btn mb-4" type="submit" value="Iniciar Sesion">
                            </form>
                            <a href="@Url.Action("RestablecerClave", "Acceso")" class="forgot-password-link">¿Se olvido la contraseña?</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</body>
</html>

ReporteCaja.AplicacionWeb/ReporteCaja.AplicacionWeb/Views/Acceso/RestablecerClave.cshtml
@model ReporteCaja.AplicacionWeb.Models.ViewModels.VMCajaUsuarioLogin
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="ES">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>GeoPedidos - Login</title>

    <link href="https://fonts.googleapis.com/css?family=Karla:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.8.95/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

    <link rel="stylesheet" href="~/css/login/login.css">
</head>
<body>
    <main class="d-flex align-items-center min-vh-100 py-3 py-md-0">
        <div class="container">
            <div class="card login-card">
                <div class="row no-gutters">
                    <div class="col-md-5">
                        <img src="~/images/login.jpg" alt="login" class="login-card-img">
                    </div>
                    <div class="col-md-7">
                        <div class="card-body">
                            <div class="brand-wrapper">
                                <img src="~/images/logo.svg" alt="logo" class="logo">
                            </div>
                            <p class="login-card-description">Recuperar Contraseña</p>
                            <form asp-controller="Acceso" asp-action="RestablecerClave" method="post">
                                <div class="form-group">
                                    <label for="email" class="sr-only">Email</label>
                                    <input type="email" asp-for="Correo" class="form-control" placeholder="Email">
                                </div>
                                <input name="login" id="login" class="btn btn-block login-btn mb-4" type="submit" value="Reestablecer Contraseña">
                            </form>
                            <a href="@Url.Action("Login", "Acceso")" class="forgot-password-link">Iniciar Sesion</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</body>
</html>